### ISSUE TITLE
Website is Down

### ISSUE THREAD

**Issue by samuelfuchs** [osgufers/osgufers.github.io#15]
Dear Support Team,

I am writing to report with great concern that the website is currently down! :scream: After discussing the issue with @vczb, I took the initiative to report this problem.

I have made several attempts to access the website from multiple devices and browsers, but unfortunately, I have not been able to load the page. :disappointed: Here are the steps I have taken to troubleshoot the issue:

- Checked my internet connection to ensure that it is working properly.
- Tried accessing the website from multiple devices and browsers.
- Cleared my browser cache and cookies.

Despite these efforts, I am still unable to access the website. 

Please let me know if you require any additional information from my end.

Best regards,
Gerson Samuel Fuchs

**Comment by vczb** [comment]
this was already resolved, the site is life on: https://blog.gufers.com/
