### ISSUE TITLE
Atualizar url do link membros

### ISSUE THREAD

**Issue by vczb** [osgufers/osgufers.github.io#6]
No blog temos o menu, e no menu tem o link membros que está redirecionando para uma página que não existe.

![image](https://user-images.githubusercontent.com/51221635/176975251-8e22314d-50ea-4bc2-bde3-2fa8af3b5029.png)

Para resolver este problema deve trocar o link por este `https://github.com/orgs/osgufers/people`

**Comment by GetulioCastro** [comment]
Feito pull request desta issue
